# Description of what this change includes
# Revision number
# Date
AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create a VPC spanning 3 Availability Zones in us-west-2

Resources:

  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC-amicel1344

  PublicSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: us-west-2a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: VPC-amicel1344-Subnet-AZ1

  PublicSubnetAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: us-west-2b
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: VPC-amicel1344-Subnet-AZ2

  PublicSubnetAZ3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: us-west-2c
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: VPC-amicel1344-Subnet-AZ3

Outputs:

  VPCId:
    Description: The ID of the created VPC
    Value: !Ref MyVPC

  SubnetAZ1:
    Description: Subnet in Availability Zone us-west-2a
    Value: !Ref PublicSubnetAZ1

  SubnetAZ2:
    Description: Subnet in Availability Zone us-west-2b
    Value: !Ref PublicSubnetAZ2

  SubnetAZ3:
    Description: Subnet in Availability Zone us-west-2c
    Value: !Ref PublicSubnetAZ3
